### ISSUE TITLE
tools/ConvexHull does not compile

### ISSUE THREAD

**Issue by svenevs** [PyMesh/PyMesh#26]
Hello, the default `tools/ConvexHull` does not compile for me.  Specifically it isn't able to find `shared_ptr`.  I added the line

`set(CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}")`

inside `tools/ConvexHull/CMakeLists.txt` to fix it (for `gcc`).

Figured I'd put this up here in case it helps somebody else.

**Comment by qnzhou** [comment]
Thanks!  Are you following the [build instructions](http://pymesh.readthedocs.io/en/latest/installation.html) in the doc?  I ask this because the flag should have been set in [Settings.cmake](https://github.com/qnzhou/PyMesh/blob/master/Settings.cmake#L9).  Maybe you overwrite `CMAKE_CXX_FLAGS` accidentally?

**Comment by svenevs** [comment]
Closing as stale.  Sorry for not responding back!  Regardless, this is definitely fixed

https://github.com/PyMesh/PyMesh/blob/a0047402e38751d0636d70d1270c61f318d68891/Settings.cmake#L51

That's the proper way to set this, not the old `CMAKE_CXX_FLAGS` fiddling approach x0
