### ISSUE TITLE
Mesh arrangement failed

### ISSUE THREAD

**Issue by chenzhaiyu** [PyMesh/PyMesh#278]
Hi,

I'm getting an error when calling `pymesh.partition_into_cells(mesh)` with
```
mesh = pymesh.load_mesh('data/double_cube.obj')
cells = pymesh.partition_into_cells(mesh)
```

The error message:
```
Input mesh is not PWN!
Traceback (most recent call last):
  File "/Users/zhaiyu/Github/cellcomplex/complex.py", line 18, in <module>
    cells = pymesh.partition_into_cells(mesh1)
  File "/Users/zhaiyu/opt/anaconda3/envs/cellcomplex/lib/python3.8/site-packages/pymesh2-0.3-py3.8-macosx-10.9-x86_64.egg/pymesh/cell_partition.py", line 49, in partition_into_cells
    cell_faces = [partition.get_cell_faces(i) for i in range(num_cells)]
  File "/Users/zhaiyu/opt/anaconda3/envs/cellcomplex/lib/python3.8/site-packages/pymesh2-0.3-py3.8-macosx-10.9-x86_64.egg/pymesh/cell_partition.py", line 49, in <listcomp>
    cell_faces = [partition.get_cell_faces(i) for i in range(num_cells)]
RuntimeError: Zero rows to stack
```

The mesh data is simply two cubes intersected:

```
# first cube
v 1 1 -1
v 1 -1 -1
v 1 1 1
v 1 -1 1
v -1 1 -1
v -1 -1 -1
v -1 1 1
v -1 -1 1

# second cube
v 2 2 0
v 2 0 0
v 2 2 2
v 2 0 2
v 0 2 0
v 0 0 0
v 0 2 2
v 0 0 2

# first cube
f 1 5 7 3
f 4 3 7 8
f 8 7 5 6
f 6 2 4 8
f 2 1 3 4
f 6 5 1 2

# second cube
f 9 13 15 11
f 12 11 15 16
f 16 15 13 14
f 14 10 12 16
f 10 9 11 12
f 14 13 9 10
```
![image](https://user-images.githubusercontent.com/24312770/106123191-eb253580-6159-11eb-9d68-712acc40cf5d.png)

Why the input mesh is not PWN in this case? and does this leads to the error or did I miss something?

**Comment by chenzhaiyu** [comment]
For future reference: it's simply doing well with triangular meshes.

**Comment by Erhannis** [comment]
> For future reference: it's simply doing well with triangular meshes.

What does that mean?  Is there a simple fix, like calling a sorting function on the mesh or something?

**Comment by chenzhaiyu** [comment]
> > For future reference: it's simply doing well with triangular meshes.
> 
> What does that mean? Is there a simple fix, like calling a sorting function on the mesh or something?

It’s been more than 5 yrs, so I may not remember all the details. As far as I recall, that function only works, or at least used to work, on triangular meshes only.

**Comment by Erhannis** [comment]
Thanks.  Even when I use only triangles, it still tells me "Input mesh is not PWN!".  When I run `convex_hull` on it before `minkowski_sum` (which is what reports non-PWN), it no longer errors - though it seems like the only thing it changed was the order of the polygons and the points in them.  I'll work on it some more and see if I can figure out what's up.

**Comment by Erhannis** [comment]
Ok, I think I figured something out, maybe all of it.  I'm using Petrify, which uses pymesh under the hood, and when I called `to_pymesh` on a mesh it created a new vertex for every corner of every triangle (perhaps a side effect of the internal representation that Petrify uses), so what pymesh sees in a tetrahedron are 12 vertices distributed across 4 triangles, rather than 4 points joined in 4 faces.  If I run `pymesh_mesh, info = pm.remove_duplicated_vertices(to_pymesh(petrify_mesh), 0.0)` before running `convex_hull(pymesh_mesh)`, it works.

Upshot of the conversation so far: 1. make sure your mesh is using triangles rather than other polygons, and 2. make sure all the vertices of your mesh have a single representation in your mesh / aren't duplicated, and use `remove_duplicated_vertices` to dedupe them if necessary.  I foresee that you would also need to make sure your model was closed and manifold and all that.  (Btw, `mesh.is_closed()` returned false for the 12-vertex collection of triangles, btw, so that may be sufficient to check if you have a problem.)
